name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install black ruff isort mypy pytest pytest-cov bandit pre-commit detect-secrets

      - name: Pre-commit
        run: |
          pre-commit install-hooks
          pre-commit run --all-files

      - name: Type check
        run: mypy .

      - name: Security scan
        run: bandit -q -r .

      - name: Tests with coverage
        run: pytest --cov --cov-report=term-missing

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./.coverage
